@startuml style
hide empty members

!unquoted procedure subtypeOf()
""&#60;&#58;""
!endprocedure

!unquoted procedure supertypeOf()
""&#62;&#58;""
!endprocedure

!unquoted procedure covariant(A)
&#43;A
!endprocedure

skinparam defaultFontSize 20
@enduml
